name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  generateControllerAll:
    authenticator: ExpressAuthentication
  generateControllerCreateUpdate:
    authenticator: ExpressAuthentication
  generateControllerDelete:
    authenticator: ExpressAuthentication
  generateControllerTypeFile:
    authenticator: ExpressAuthentication