name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createServ:
    authenticator: ExpressAuthentication
  deleteServ:
    authenticator: ExpressAuthentication
  readServAll:
    authenticator: ExpressAuthentication
  updateServ:
    authenticator: ExpressAuthentication